spring:
  application:
    name: order-command
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: command
      properties:
        spring:
          json:
            value:
              default:
                type: com.pedrocomitto.poc.orderquery.domain.event.OrderEvent
            trusted:
              packages: '*'
            use:
              type:
                headers: false
